package.json
yarn.lock

nuxt-property-decoratorを追加しました。

nuxt-property-decoratorを追加

---

components/02-molecules/Card.vue
pages/index.vue
types/components/02-molecules/card.ts

カードコンポーネントの実装

---

components/01-atoms/Logo.vue
components/02-molecules/Card.vue
components/02-molecules/RoomLogo.vue
components/03-organisms/header.vue
layouts/default.vue
layouts/empty.vue
layouts/error.vue
pages/index.vue
pages/sample/index.vue
types/components/02-molecules/card.ts
types/components/02-molecules/roomLogo.ts

CompositionAPIでコンポーネントを書き換えました。

CompositionAPIの導入

---

components/02-molecules/RequestMusicOverview.vue
pages/index.vue

楽曲リクエストコンポーネントを作る

---

components/01-atoms/TextInput.vue
pages/index.vue
pages/playground.vue
tailwind.config.js

・テキストインプット作りました。
・コンポーネントのサンプルはpages/playgroundに移動しました。

テキストインプットコンポーネント作りました

---

components/03-organisms/Header.vue

`layout/default.vue`のインポートエラーを修正しました。

インポートエラーの修正

---

components/01-atoms/HeaderText.vue
pages/playground.vue
tailwind.config.js

resolved #24 
--
縁取りありの実装厳しかったので、一旦縁取りなしでつくりました
以下のブラウザで動作確認済み
- Google Chrome
- Safar

ヘッダーコンポーネントつくりました

---

core/01-models/music/index.ts
core/01-models/room/index.ts
core/01-models/user/index.ts
types/params/requestMusic.ts

モック用にEntityのModelを追加しました。プロパティ変わりそうだけどそれは後で対応します。

EntityとParamsの追加

---

components/01-atoms/Logo.vue
components/03-organisms/Header.vue

ヘッダーの高さの変更

---

components/01-atoms/Container.vue
components/01-atoms/HeaderText.vue
pages/playground.vue
pages/room/_displayID/result/index.vue

Containerコンポーネントの実装

---

nuxt.config.ts
plugins/axios-accessor.ts
plugins/axios.ts
utils/snakeToCamel.ts

nuxt.config.tsの設定の変更

---

core/01-models/googleLogin/index.ts
core/01-models/userCredentials/index.ts
core/02-repositories/UserCredentials/index.ts
core/02-repositories/googleLogin/index.ts
core/02-repositories/loggedInGoogle/index.ts
core/03-composables/useGoogleLogin.ts
core/03-composables/useLocalStorageUserCredentials.ts
core/03-composables/useLoggedinGoogle.ts
core/03-composables/useUserCredentials.ts
middleware/auth.ts
nuxt.config.ts
pages/api/google/callback/index.vue
pages/mc/login.vue
plugins/axios.ts
plugins/nuxtInstance.ts
types/params/loggedInGoogleParams.ts
types/query/googleLoginCallbackQuery.ts
utils/nuxtInstance.ts

ログイン機能のつなぎ込み

---

components/02-molecules/RoomLogo.vue
pages/room/_displayID/index.vue
pages/room/_displayID/result/index.vue

dj-48-design/me01-search

---

core/03-composables/useGoogleLogin.ts
pages/index.vue
pages/mc/login.vue

Googleログイン周りのバグ修正

---

plugins/axios.ts

middlewareでキャメルケースをスネークケースにするぜ！

キャメルケースをスネークケースにするミドルウェアのつなぎ込み

---

components/02-molecules/RequestMusicOverview.vue
components/04-containers/MemberOtayoriModal.vue
pages/playground.vue
tailwind.config.js

Issue 50 feature/member request

---

components/02-molecules/RequestMusicOverview.vue
components/04-containers/MemberMusicSelect.vue
components/04-containers/MemberOtayori.vue
core/02-repositories/requestMusic/index.ts
core/03-composables/useLoading.ts
core/03-composables/useMusic.ts
core/03-composables/useRequestMusic.ts
core/03-composables/useTextFieldComponent.ts
pages/room/_displayID/result/index.vue
types/pages/room/_displayID/result/index.ts

音楽リクエスト画面の実装終わりました。
あとはAPIつなぎこむだけやあああああ

音楽リクエスト画面の実装

---

core/02-repositories/googleLogin/index.ts
core/02-repositories/loggedInGoogle/index.ts

Googleログイン周りのリポジトリの修正

---

components/01-atoms/SelectInput.vue
pages/mc/room/create/index.vue

Issue 63 feature/room create

---

components/04-containers/MemberMusicSelect.vue
pages/room/_displayID/result/index.vue

fix: modal-margin

---

components/02-molecules/Card.vue
components/02-molecules/RequestMusicOverview.vue
components/04-containers/MemberMusicSelect.vue
components/04-containers/MemberOtayori.vue
core/01-models/music/helper.ts
core/01-models/music/index.ts
pages/playground.vue
pages/room/_displayID/result/index.vue
types/components/music_overview.ts

resolved #92 
データの使い回しと内容が完全に同じだったので、```card```と```RequestMusicOverview```を```MusicOverview```に統合しました。

Issue 92 refactoring/member design

---

components/02-molecules/RoomLogo.vue
pages/room/_displayID/index.vue

Issue 94 design/music-search

---

components/04-containers/MemberMusicSelect.vue
core/01-models/music/helper.ts
core/01-models/room/index.ts
core/01-models/user/index.ts
core/02-repositories/UserCredentials/index.ts
core/02-repositories/fetchMusic/index.ts
core/02-repositories/googleLogin/index.ts
core/02-repositories/loggedInGoogle/index.ts
core/02-repositories/requestMusic/index.ts
core/03-composables/useGoogleLogin.ts
core/03-composables/useLocalStorageUserCredentials.ts
core/03-composables/useLoggedinGoogle.ts
plugins/axios.ts

データフロー周りの命名規則の修正

---

components/02-molecules/LoadingOverlay.vue

画面全体に覆いかぶさる感じのLoadingコンポーネントを作りました。

LoadingOverlayコンポーネントの作成

---

core/01-models/createRoom/index.ts
core/02-repositories/createRoom/index.ts
core/03-composables/useCreateRoom.ts
layouts/default.vue
pages/mc/room/create/index.vue
types/params/createRoom.ts

ルーム作成画面の追加

---

core/02-repositories/UserCredentials/index.ts
core/03-composables/useLocalStorageUserCredentials.ts
plugins/axios.ts

localStorageにtokenがなかったらバグり散らしてたので直しました。

api-token周りのエラーハンドリング

---

plugins/axios.ts
utils/camelToSnake.ts
utils/snakeToCamel.ts

converterのロジックが配列食わせたときにうまく言ってなかったので直しました。

converterのロジック修正

---

core/02-repositories/googleLogin/index.ts
core/02-repositories/loggedInGoogle/index.ts

[fix] google login api endpoint

[fix] google login api endpoint

---

environments/production.ts

[update] environment variables for production

---

components/01-atoms/SelectInput.vue
core/02-repositories/createRoom/index.ts
pages/mc/room/create/index.vue
types/data/providerName.ts
types/params/createRoom.ts

ルーム作成画面のアップデート

---

package.json

buildコマンドの変更

---

nuxt.config.ts

nuxt.config.tsを変えました。

---

package.json

cross-envをdevDependenciesからdependenciesに変えました

[move] cross-env devDependencies to dependencies

---

package.json

[update] build command

---

core/01-models/room/index.ts
core/02-repositories/fetchRooms/index.ts
core/03-composables/useFetchRooms.ts
pages/mc/index.vue

ルーム全件取得APIのつなぎこみ

---

yarn.lock

[update] browserslist

---

components/03-organisms/Header.vue
layouts/default.vue
pages/mc/index.vue
pages/mc/music/apple-music-login/index.vue
pages/mc/room/_displayID/index.vue
pages/mc/room/_displayID/settings/index.vue
pages/mc/room/create/index.vue

いい感じのネオンのボーダーつけれるようにあったら復活させたい

ヘッダーのデザインを修正しました

---

core/01-models/registerSpotifyToken/index.ts
core/01-models/spotifyLogin/index.ts
core/02-repositories/registerSpotifyToken/index.ts
core/02-repositories/spotifyLogin/index.ts
core/03-composables/useRegisterSpotifyToken.ts
core/03-composables/useSpotifyLogin.ts
environments/development.ts
environments/production.ts
middleware/auth.ts
pages/mc/index.vue
types/params/registerSpotifyTokenParams.ts
utils/constants.ts

Spotify連携の実装

---

components/01-atoms/Modal.vue
components/04-containers/MemberMusicSelect.vue
components/04-containers/MemberOtayori.vue
core/01-models/music/helper.ts
core/01-models/music/index.ts
core/02-repositories/fetchMusic/index.ts
core/02-repositories/requestMusic/index.ts
core/03-composables/useFetchMusic.ts
core/03-composables/useModal.ts
core/03-composables/useRequestMusic.ts
mock/music.ts
pages/room/_displayID/index.vue
pages/room/_displayID/result/index.vue
types/pages/room/_displayID/result/index.ts
types/params/fetchMusicParams.ts
utils/getQuery.ts

音楽検索画面をモックで実装

---

core/01-models/roomOverview/index.ts
core/02-repositories/fetchRoomOverview/index.ts
core/03-composables/useFetchRoomOverview.ts
core/03-composables/useTextField.ts
pages/room/_displayID/index.vue
types/params/roomOverviewParams.ts

ルーム概要の取得APIのつなぎこみしました！
404が返ってきたときのハンドリングもバッチリかも！

ルーム概要の取得APIのつなぎこみ

---

components/04-containers/MemberMusicSelect.vue
core/03-composables/useFetchMusics.ts

音楽検索周りのロジックの修正

---

components/02-molecules/Background.vue
package.json
pages/room/_displayID/index.vue
pages/room/_displayID/result/index.vue
tailwind.config.js
yarn.lock

たこやき案の背景を実装しました

---

core/02-repositories/requestMusic/index.ts
core/03-composables/useRequestMusic.ts
pages/room/_displayID/result/index.vue

音楽リクエスト機能の実装

---

core/03-composables/useRequestMusic.ts

音楽リクエストのエラー

---

core/01-models/fetchRoomDetail/index.ts
core/02-repositories/fetchRoomPlaylist/index.ts
core/03-composables/useFetchRoomDetail.ts
core/03-composables/useRoomSettings.ts
pages/mc/room/_displayID/index.vue
pages/mc/room/_displayID/settings/index.vue
types/components/roomDetail.ts
types/params/fetchRoomPlaylistParams.ts

ルーム詳細画面のつなぎ込み

---

pages/mc/room/_displayID/index.vue

ルーム詳細画面の修正

---

nuxt.config.ts

なんかOGP設定できてなくね？？？

---

pages/index.vue

ルートページにロゴを表示させました

---

core/03-composables/useAccountDetail.ts
core/03-composables/useFetchRoomDetail.ts
core/03-composables/useGoogleLogin.ts
core/03-composables/useSpotifyLogin.ts
environments/config.ts
environments/development.ts
environments/production.ts
middleware/auth.ts
middleware/config.ts
nuxt.config.ts
utils/constants.ts

環境変数の突っ込み方変えました

---

components/02-molecules/UserRequestCard.vue
core/01-models/userRequest/helper.ts
core/01-models/userRequest/index.ts
core/02-repositories/fetchUserRequests/index.ts
core/03-composables/useFetchRoomDetail.ts
package.json
pages/mc/room/_displayID/index.vue
plugins/fontawesome.ts
types/components/userRequestCard.ts
types/params/fetchUserRequests.ts
yarn.lock

letter to tweet

---

pages/mc/room/create/index.vue

delete: apple-music

---

pages/mc/room/create/index.vue

Reverts lit-kansai/dj_system-portal#213

Revert "delete: apple-music"

---

core/03-composables/useUserCredentials.ts
plugins/axios.ts

トークンの有効期限が切れてたら自動でログアウトさせる機能を実装しました。

トークンの有効期限が切れてたら自動でログアウトさせる

---

components/04-containers/MemberMusicSelect.vue
components/04-containers/MemberOtayori.vue
core/03-composables/useFetchMusics.ts
core/03-composables/useRequestMusic.ts
core/03-composables/useRequestMusicModal.ts
core/03-composables/useRequestMusicModalState.ts
pages/room/_displayID/result/index.vue
types/data/urlParamsKey.ts

モーダル周りのリファクタリング

---

components/04-containers/MemberMusicSelect.vue
components/04-containers/MemberOtayori.vue
core/03-composables/useFetchMusics.ts
core/03-composables/useRequestMusic.ts
core/03-composables/useRequestMusicModal.ts
core/03-composables/useRequestMusicModalState.ts
pages/room/_displayID/result/index.vue
types/data/urlParamsKey.ts

Reverts lit-kansai/dj-system-client-member#245

Revert "モーダル周りのリファクタリング"

---

core/02-repositories/radioName/index.ts

radioName repositoryの実装
